/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Manvel' at '12/20/16 10:46 PM' with Gradle 2.14.1
 *
 * @author Manvel, @date 12/20/16 10:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
